name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SUPER_OLEG_PAT }}
        fetch-depth: 0

    - name: Git Identity
      run: |
        git config --global user.name 'SuperOleg39'
        git config --global user.email 'SuperOleg39@users.noreply.github.com'

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install
      run: |
        npm i -g lerna@^3.22.1
        npm run bootstrap

    - name: Create release commit and tag
      run: |
        npm run version -- --no-push

    - name: Push release commit and tag
      run: git push --follow-tags
